# Generated by Django 4.0.3 on 2022-04-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wl',
            name='no',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
