# Generated by Django 4.0.3 on 2022-04-21 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_wl_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wl',
            name='no',
        ),
        migrations.AlterField(
            model_name='wl',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wl',
            name='wl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.market'),
        ),
    ]
